### PR TITLE
Restructuring, reformatting, and reusing

### PR DESCRIPTION
**Pull request by sagefantasma**
I was curious to learn how this trainer worked and decided to do some remodeling. I've tested and made sure everything that was working with master is still working with the restructuring.

Forms are now informatively named, there's a lot more shared code and deduplication so any changes that get made in the future have fewer points of failure.

Feel free to ignore this PR, I just was really impressed with what you have here and wanted to contribute what I could back while I poked through the code to learn how it worked :^)

### CODE REVIEW

**Comment by ANTIBigBoss** [comment]
Oh nice this is really well done and organized! Mine was a very quick and dirty implementation I did as I was learning how the game's memory worked. I kept meaning to reorganize similar to this so you probably saved me a lot of time haha. I'll give this a test out and commit it to the main after I confirm functionality still works!

I've been looking into a way to not have to hardcode all the memory (Make it more resistent to updates from Konami) so I'll probably add that into your implementation once I get it fully solved.

Thanks again for all this!

**Review by ANTIBigBoss — APPROVED** [review]
All functionality still working as it should great work! Approving these changes and going to add to master build!

**Comment by sagefantasma** [comment]
Glad to help! Feel free to hit me up with questions/if there's anything else I can help with. I really enjoyed going through this and would be happy to contribute more when and where I can :)

**Comment by ANTIBigBoss** [comment]
Absolutely I welcome the help! If you have Discord I can be reached at the same username "ANTIBigBoss" on there, I'm a lot more active on there! I got plans to make more of these for all the MGS games in the collection wherever my free time allows me haha!

**Pull request merged**
